services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
     - mysql-data:/var/lib/mysql
    networks:
      backend:

volumes:
  mysql-data:

networks:
  backend: